### ISSUE TITLE
[Feature]: A Linux Setup Guide

### ISSUE THREAD

**Issue by NishchayKQ** [OPCODE-Open-Spring-Fest/SlitherCraft#1]
### So, what is it about?

Linux Setup also gives a way to remove Visual Studio Dependency, making development possible on OS other than windows  

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by sanghaibiraj** [comment]
Avoid Readme/Setup/Requirements Contributions, stick to C++/SFML for this Repo. But Thanks for Informing.
